version: '3.4'

networks:
  cqrs-api-docker-postgres-dev:
    driver: bridge 

services:
  cqrs-api-docker-postgres-dev:
    image: cqrs-api-docker-postgres-dev:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=CqrsApiDatabase;username=postgres;password=postgres"
    networks:
      - cqrs-api-docker-postgres-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "CqrsApiDatabase"
    networks:
      - cqrs-api-docker-postgres-dev
volumes:
  db_volume: