version: "3.4"

services:
  api:
    build:
      context: .
      args:
        VERSION: '1.2.3.4'
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    environment:
      SqlServerConnectionString: "Server=db;Database=MOVIES_DOCKER;User Id=sa;Password=x2yiJt!Fs;TrustServerCertificate=true;"
      ShouldMigrate: "true"
    depends_on:
      - db
  
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1444:1433"
    
    environment:
      SA_PASSWORD: "x2yiJt!Fs"
      ACCEPT_EULA: "Y"