trigger: none
pr: none

variables:
  - name: solution
    value: 'MoviesAPI.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: projectPath
    value: 'MoviesAPI.Core/MoviesAPI.Core.csproj'

stages:
  - stage: 'Build_Test'
    jobs:
      - job: "Build"
        displayName: 'Build Test & Drop artifacts'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self
            fetchDepth: 0

          - task: gitversion/setup@0
            displayName: 'GitVersion Setup'
            inputs:
              versionSpec: '5.9.x'

          - task: gitversion/execute@0
            displayName: 'GitVersion Execute'

          - bash: echo $Action$BuildVersion
            displayName: 'Set Build Version'
            env:
              Action: '##vso[build.updatebuildnumber]'
              BuildVersion: $(GitVersion.SemVer)

          - task: UseDotNet@2
            displayName: 'Install .NET 6.x SDK'
            inputs:
              packageType: sdk
              version: 6.x

          - task: DotNetCoreCLI@2
            displayName: 'Dotnet Restore'
            inputs:
              command: 'restore'
              projects: '$(solution)'
              restoreArguments: '--locked-mode'
              arguments: '--verbosity minimal'

          - task: DotNetCoreCLI@2
            displayName: 'Dotnet build $(buildConfiguration)'
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '-p:Version=$(GitVersion.SemVer) --configuration $(buildConfiguration) --no-restore'

          - task: DotNetCoreCLI@2
            displayName: 'Dotnet Publish'
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '$(projectPath)'
              arguments: '-c $(buildConfiguration) -p:Version=$(GitVersion.SemVer) -o $(Build.ArtifactStagingDirectory)/$(buildConfiguration) --no-build'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: 'yaml_env'
    displayName: 'Deploy Movies dev'
    dependsOn: Build_Test
    condition: succeeded('Build_Test')
    jobs:
      - deployment: Deploy_Movies_Dev
        displayName: 'Deploy Movies dev'
        variables:
          - group: MOVIES_SETTINGS
          - group: devtest.team_wildcard_certificate
          - group: Movies_IIS_YAML_Settings
        environment:
          name: yaml
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: IISWebAppManagementOnMachineGroup@0
                  inputs:
                    EnableIIS: true
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'CreateOrUpdateWebsite'
                    WebsiteName: '$(IISSiteName)'
                    WebsitePhysicalPath: '$(IISPhysicalPath)'
                    AddBinding: true
                    Bindings: |
                      {
                          bindings: [
                            {
                              "protocol":"http",
                              "ipAddress":"*",
                              "hostname":"$(IISSiteHostName)",
                              "port":"80",
                              "sslThumbprint":"",
                              "sniFlag":false
                            },
                            {
                              "protocol":"https",
                              "ipAddress":"*",
                              "hostname":"$(IISSiteHostName)",
                              "port":"443",
                              "sslThumbprint":"$(certificate_thumbprint)",
                              "sniFlag":false
                            }
                          ]
                      }
                    CreateOrUpdateAppPoolForWebsite: true
                    ConfigureAuthenticationForWebsite: true
                    AppPoolNameForWebsite: '$(IISSiteName)'
                    DotNetVersionForWebsite: 'No Managed Code'
                    PipeLineModeForWebsite: 'Integrated'
                    AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
                    AnonymousAuthenticationForWebsite: true
                    BasicAuthenticationForWebsite: false
                    WindowsAuthenticationForWebsite: false

                - task: IISWebAppDeploymentOnMachineGroup@0
                  displayName: 'IIS Web App Deploy'
                  inputs:
                    WebSiteName: '$(IISSiteName)'
                    TakeAppOfflineFlag: true
                    Package: '$(Pipeline.Workspace)/drop/Release/*.zip'
                    JSONFiles: '**/appsettings.json'
                    
  - stage: 'yaml_virtual_env'
    displayName: 'Deploy Movies Virtual dev'
    dependsOn: yaml_env
    condition: succeeded('yaml_env')
    jobs:
      - deployment: Deploy_Movies_Virtual_Dev
        displayName: 'Deploy Movies Virtual dev'
        variables:
          - group: MOVIES_SETTINGS
          - group: devtest.team_wildcard_certificate
          - group: Movies_IIS_Virtual_YAML_Settings
        environment:
          name: yaml
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop
                  
                - task: IISWebAppManagementOnMachineGroup@0
                  displayName: 'Manage IISWebApplication'
                  inputs:
                    IISDeploymentType: IISWebApplication
                    WebsiteName: '$(IISSiteName)'
                    WebsitePhysicalPath: '$(IISPhysicalPath)'
                    CreateOrUpdateAppPoolForWebsite: true
                    AppPoolNameForWebsite: '$(IISSiteName)'
                    DotNetVersionForWebsite: 'No Managed Code'
                    ParentWebsiteNameForApplication: '$(IISSiteName)'
                    VirtualPathForApplication: '/$(VirtualApplicationName)'
                    PhysicalPathForApplication: '$(IISPhysicalPath)'
                    CreateOrUpdateAppPoolForApplication: true
                    AppPoolNameForApplication: '$(VirtualApplicationPool)'
                    DotNetVersionForApplication: 'No Managed Code'

                - task: IISWebAppDeploymentOnMachineGroup@0
                  displayName: 'Deploy IIS Website'
                  inputs:
                    WebSiteName: '$(IISSiteName)'
                    VirtualApplication: '$(VirtualApplicationName)'
                    Package: '$(Pipeline.Workspace)/drop/Release/*.zip'
                    TakeAppOfflineFlag: true
                    JSONFiles: '**/appsettings.json'
                    
# TO TEST SNI WITH DIFFERENT DOMAINS

  - stage: 'test_sni'
    displayName: 'Deploy Movies dev'
    dependsOn: Build_Test
    condition: succeeded('Build_Test')
    jobs:
      - deployment: Deploy_Movies_Dev
        displayName: 'Deploy Movies dev'
        variables:
          - group: MOVIES_SETTINGS
          - group: razumovsky.me_wildcard_certificate
          - group: Movies_IIS_YAML_Settings
        environment:
          name: testsni
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: IISWebAppManagementOnMachineGroup@0
                  inputs:
                    EnableIIS: true
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'CreateOrUpdateWebsite'
                    WebsiteName: '$(IISSiteName)'
                    WebsitePhysicalPath: '$(IISPhysicalPath)'
                    AddBinding: true
                    Bindings: |
                      {
                          bindings: [
                            {
                              "protocol":"http",
                              "ipAddress":"*",
                              "hostname":"$(IISSiteHostName)",
                              "port":"80",
                              "sslThumbprint":"",
                              "sniFlag":false
                            },
                            {
                              "protocol":"https",
                              "ipAddress":"*",
                              "hostname":"$(IISSiteHostName)",
                              "port":"443",
                              "sslThumbprint":"$(certificate_thumbprint)",
                              "sniFlag":false
                            }
                          ]
                      }
                    CreateOrUpdateAppPoolForWebsite: true
                    ConfigureAuthenticationForWebsite: true
                    AppPoolNameForWebsite: '$(IISSiteName)'
                    DotNetVersionForWebsite: 'No Managed Code'
                    PipeLineModeForWebsite: 'Integrated'
                    AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
                    AnonymousAuthenticationForWebsite: true
                    BasicAuthenticationForWebsite: false
                    WindowsAuthenticationForWebsite: false

                - task: IISWebAppDeploymentOnMachineGroup@0
                  displayName: 'IIS Web App Deploy'
                  inputs:
                    WebSiteName: '$(IISSiteName)'
                    TakeAppOfflineFlag: true
                    Package: '$(Pipeline.Workspace)/drop/Release/*.zip'
                    JSONFiles: '**/appsettings.json'