trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: PublishApp
    steps:
      - checkout: self

      - script: docker build -t my-dotnet-publish-container -f Dockerfile .
        displayName: 'Build Docker Container'

      - script: docker volume create my-publish-volume
        displayName: 'Create Docker Volume'

      - script: docker run --name my-temp-container -v my-publish-volume:/app/publish my-dotnet-publish-container
        displayName: 'Run Docker Container'

      - script: docker cp my-temp-container:/app/publish $(Build.ArtifactStagingDirectory)/publish
        displayName: 'Copy Published Files'

      - script: docker rm my-temp-container
        displayName: 'Remove Temporary Container'

      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: 'published_app'
          pathToPublish: $(Build.ArtifactStagingDirectory)/publish