trigger: none
pr: none

variables:
  - name: dockerRepository
    value: 'movies-api-k8s'
  - name: dockerUser
    value: 'petrokolosov'
  - name: dockerImage
    value: 'moviesapi'

stages:
  - stage: "docker_webapi_build_push"
    displayName: "Docker Web API build push"
    jobs:
      - job: Build_Push_Docker_Image
        displayName: "Build push docker image"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            fetchDepth: 0

          - task: gitversion/setup@0
            displayName: 'GitVersion Setup'
            inputs:
              versionSpec: '5.9.x'

          - task: gitversion/execute@0
            displayName: 'GitVersion Execute'
            inputs:
              updateAssemblyInfo: true

          - bash: echo $Action$BuildVersion
            displayName: 'Set Build Version'
            env:
              Action: '##vso[build.updatebuildnumber]'
              BuildVersion: $(GitVersion.SemVer)

          - bash: |
              IMAGE_FULL_NAME="$USER/$REPOSITORY:$VERSION"
              echo "Image full name: $IMAGE_FULL_NAME"
              docker build -t "$IMAGE_FULL_NAME" --build-arg VERSION=$VERSION .
              docker build -t "$USER/$REPOSITORY:latest" --build-arg VERSION=$VERSION .
            env:
              REPOSITORY: ${{ variables.dockerRepository }}
              VERSION: $(GitVersion.SemVer)
              USER: ${{ variables.dockerUser }}
            displayName: 'Build Docker Image'

          - bash: docker images
            displayName: 'List Docker Images'

          - task: Docker@2
            displayName: 'Push to DockerHub'
            inputs:
              containerRegistry: 'DockerHub_Connection'
              repository: '${{ variables.dockerUser }}/${{ variables.dockerRepository }}'
              command: push
              tags: |
                latest
                $(GitVersion.SemVer)